services:
  db:
    container_name: postgres_database
    image: postgres:16.3
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Cambia a volumen nombrado
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=postgres
    restart: unless-stopped
    ports:
      - "5433:5432"

  pgAdmin:
    depends_on:
      - db
    image: dpage/pgadmin4:8.6
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "8080:80"
    environment:
      - PGADMIN_DEFAULT_PASSWORD=123456
      - PGADMIN_DEFAULT_EMAIL=superman@google.com
    restart: unless-stopped

volumes:
  postgres_data:
  pgadmin_data: